-- MySQL Script generated by MySQL Workbench
-- Fri May  4 17:33:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema project_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project_db` DEFAULT CHARACTER SET utf8 ;
USE `project_db` ;

-- -----------------------------------------------------
-- Table `project_db`.`periodical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_db`.`periodical` (
  `idperiodical` INT(11) NOT NULL AUTO_INCREMENT,
  `namePer` VARCHAR(100) NOT NULL,
  `pricePer` INT(11) NOT NULL,
  `short_description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`idperiodical`),
  UNIQUE INDEX `namePer_UNIQUE` (`namePer` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_db`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_db`.`article` (
  `idarticle` INT(11) NOT NULL AUTO_INCREMENT,
  `nameArt` VARCHAR(200) NOT NULL,
  `date` DATE NOT NULL,
  `idperiodical` INT(11) NOT NULL,
  `text` VARCHAR(20000) NOT NULL,
  PRIMARY KEY (`idarticle`, `idperiodical`),
  INDEX `fk_article_periodical_idx` (`idperiodical` ASC),
  CONSTRAINT `fk_article_periodical`
    FOREIGN KEY (`idperiodical`)
    REFERENCES `project_db`.`periodical` (`idperiodical`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_db`.`user` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER',
  `money` INT(11) NOT NULL DEFAULT '0',
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_db`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_db`.`payment` (
  `idpayment` INT(11) NOT NULL AUTO_INCREMENT,
  `pricePay` INT(11) NOT NULL,
  `iduser` INT(11) NOT NULL,
  PRIMARY KEY (`idpayment`),
  INDEX `fk_payment_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_payment_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `project_db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_db`.`periodical_has_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_db`.`periodical_has_payment` (
  `idperiodical` INT(11) NOT NULL,
  `idpayment` INT(11) NOT NULL,
  PRIMARY KEY (`idperiodical`, `idpayment`),
  INDEX `fk_periodical_has_payment_payment1_idx` (`idpayment` ASC),
  INDEX `fk_periodical_has_payment_periodical1_idx` (`idperiodical` ASC),
  CONSTRAINT `fk_periodical_has_payment_payment1`
    FOREIGN KEY (`idpayment`)
    REFERENCES `project_db`.`payment` (`idpayment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_periodical_has_payment_periodical1`
    FOREIGN KEY (`idperiodical`)
    REFERENCES `project_db`.`periodical` (`idperiodical`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_db`.`user_has_periodical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_db`.`user_has_periodical` (
  `iduser` INT(11) NOT NULL,
  `idperiodical` INT(11) NOT NULL,
  PRIMARY KEY (`iduser`, `idperiodical`),
  INDEX `fk_user_has_periodical_periodical1_idx` (`idperiodical` ASC),
  INDEX `fk_user_has_periodical_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_user_has_periodical_periodical1`
    FOREIGN KEY (`idperiodical`)
    REFERENCES `project_db`.`periodical` (`idperiodical`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_periodical_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `project_db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
